### ISSUE TITLE
Feature Request: Announce winner when the timer completes.

### ISSUE THREAD

**Issue by JustinLoecher** [MarcelineVQ/LootBlare#1]
Hello, would it be possible to add a function to this that announces the highest roll when the timer ends in raid warning?  Would be nice so people know rolling has closed.

**Comment by MarcelineVQ** [comment]
No sorry the addon is intended just to draw your attention to the loot being rolled because it's so easy to miss. This is why the countdown is customizable, so people can choose their personal desired level of annoyance.
If you want something with that feature feel free to take anything you need from this addon.
